### ISSUE TITLE
MIT license may not be appropriate.

### ISSUE THREAD

**Issue by th3w1zard1** [NickHugi/KotorDotNET#1]
I notice both PyKotor and this repo are licensed under the MIT license. Both of those seem to be default for GitHub. I think it's important to choose a specific one right off the bat.

Here's some short summary comparisons from various resources I've found on the topic.

    Sharing & Improving (Reciprocity):
        GPLv3: "If you use my stuff and make it better, you have to share your improvements." It's kind of like a community potluck where everyone brings a dish and gets to eat from what others bring too.
        MIT: "You can use my stuff. If you make it better, you can keep it to yourself." Like someone giving away cake and you can either share your slice or keep it.

    Selling & Making Money:
        Both GPLv3 and MIT allow others to sell the software.
        The big difference is about what happens after selling.
        GPLv3: "If you sell my stuff, you must give buyers the same freedoms I gave you. They should get the 'recipe' too (the code) and they can also sell it, but with the same rules." This means no hidden secret ingredients!
        MIT: "If you sell my stuff, you can keep the 'recipe' secret." It’s like selling a cake without giving out the ingredients or how to make it.

    Credits & Ownership:
        GPLv3: You have to give credit and can't claim the software as just yours. "You can use and sell, but always remember to tell them where you got it from."
        MIT: Just a simple "Say thanks to the original creator and you're good to go."

    Stealing Work:
        Your concern about "stealing" is kinda right but let's be clear:
        GPLv3: It makes sure that the community benefits from changes. It's not about stopping people from making money, but about keeping sharing in the loop.
        MIT: It's super permissive. Someone could take the code, make changes, sell it, and not share their improvements.

    Future Proofing:
        GPLv3: The license has protections against potential future legal issues, like software patents. So, it's like having a strong fence around your garden.
        MIT: It's simpler but doesn’t offer those extra protections.

If you want your code to be part of a community where everyone helps each other out and shares their improvements, GPLv3 is a solid choice. If you just want to give your code to the world with minimal strings attached, then MIT is more in line with that. I simply believe it's important to recognize the differences and make a conscious decision to choose one.

**Comment by NickHugi** [comment]
I have gone ahead and updated license to be GPLv3. Better late than never, I guess.
